name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Action dependencies
        run: pip install mypy autopep8

      - name: Install Project dependencies
        run: >
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run linters
        uses: wearerequired/lint-action@master
        with:
          auto_fix: true
          commit: false
          mypy: true
          mypy_auto_fix: false
          autopep8: true
          autopep8_auto_fix: true
          autopep8_args: >
            --max-line-length 120
      - name: Reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: Autopep8
