name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: pip

      - name: Install Action dependencies
        run: pip install mypy autopep8

      - name: Install Project dependencies
        run: >
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run linters
        uses: daniel-atanasov/lint-action@feature/auto-commit
        with:
          auto_fix: true
          auto_commit: false
          mypy: false
          mypy_args: >
            --follow-imports=silent
            --ignore-missing-imports
            --implicit-optional
            --no-strict-optional
          autopep8: true
          autopep8_args: >
            --max-line-length 120

      - name: suggester / lint
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: lint
